def my_creds():
	CONSUMER_KEY = 'XXXXXXXXXXXXXXXXXXXX'
	CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXX'
	OAUTH_TOKEN = 'XXXXXXXXXXXXXXXXXXXX'
	OAUTH_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXX'

	return OAUTH_TOKEN, OAUTH_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_SECRET
